**Part 1: Theoretical Questions**



## Q1. What is different data structures used in Tensorflow ? Give some examples
---

### TensorFlow, a popular open-source machine learning framework, provides several different data structures to efficiently handle and manipulate data for building and training machine learning models. Some of the key data structures used in TensorFlow include:

1. `Tensors` : Tensors are the fundamental building blocks in TensorFlow. They are n-dimensional arrays that represent the data in the computation graph. Tensors can be scalars (0-dimensional), vectors (1-dimensional), matrices (2-dimensional), or higher-dimensional arrays. TensorFlow tensors can be created using functions like tf.constant(), tf.Variable(), and by performing various operations on existing tensors.

In [2]:
import tensorflow as tf

# Creating tensors
scalar = tf.constant(10)
vector = tf.constant([1, 2, 3, 4, 5, 6])
matrix = tf.constant([[1, 2], [3, 4]])

In [3]:
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [4]:
vector

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6], dtype=int32)>

In [5]:
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

2. `Variables`: TensorFlow Variables are special tensors that can hold mutable state. They are often used to store model parameters that need to be learned during training. Variables are typically initialized with some initial values and then updated through operations.

In [8]:
# Creating a variable
initial_value = tf.random.normal(shape=(6, 6))
model_weights = tf.Variable(initial_value)

In [9]:
initial_value

<tf.Tensor: shape=(6, 6), dtype=float32, numpy=
array([[-2.3131151 ,  0.0440109 ,  0.29744846,  1.8803967 ,  0.03337547,
         0.97574615],
       [ 0.43562785, -1.4715364 , -0.95558655,  0.00952041,  0.74801004,
        -0.30931878],
       [ 0.3415289 ,  0.62640417,  0.883265  ,  0.43127805,  0.29796487,
         1.438003  ],
       [-0.9760235 , -2.010557  ,  0.5239883 , -0.42228982, -0.41784635,
         0.30849388],
       [-0.01213103, -0.6861366 , -0.7718909 ,  0.5777891 , -1.2169088 ,
        -0.10302201],
       [-2.6531467 , -0.89223605,  0.825566  , -0.80281615, -0.2876945 ,
         0.44386384]], dtype=float32)>

In [10]:
model_weights

<tf.Variable 'Variable:0' shape=(6, 6) dtype=float32, numpy=
array([[-2.3131151 ,  0.0440109 ,  0.29744846,  1.8803967 ,  0.03337547,
         0.97574615],
       [ 0.43562785, -1.4715364 , -0.95558655,  0.00952041,  0.74801004,
        -0.30931878],
       [ 0.3415289 ,  0.62640417,  0.883265  ,  0.43127805,  0.29796487,
         1.438003  ],
       [-0.9760235 , -2.010557  ,  0.5239883 , -0.42228982, -0.41784635,
         0.30849388],
       [-0.01213103, -0.6861366 , -0.7718909 ,  0.5777891 , -1.2169088 ,
        -0.10302201],
       [-2.6531467 , -0.89223605,  0.825566  , -0.80281615, -0.2876945 ,
         0.44386384]], dtype=float32)>

3. `Constants`: Constants are tensors with fixed values that remain unchanged throughout the computation. They are often used for providing constant inputs or values to the computation graph.

In [11]:
# Creating a constant
pi = tf.constant(3.14159)

In [12]:
pi

<tf.Tensor: shape=(), dtype=float32, numpy=3.14159>

4. `Placeholders (Deprecated)`: In older versions of TensorFlow (before TensorFlow 2.0), placeholders were used to feed data into the computation graph during training. However, placeholders have been deprecated in favor of the new tf.data API and eager execution in TensorFlow 2.0 and later.

5. `Sparse Tensors`: Sparse tensors are designed to efficiently represent tensors with a large number of zero elements. They are useful for tasks involving sparse data, such as natural language processing or certain types of neural networks.

In [13]:
indices = [[0, 1], [1, 2]]
values = [1, 2]
shape = [3, 4]
sparse_tensor = tf.SparseTensor(indices, values, shape)

In [14]:
sparse_tensor

SparseTensor(indices=tf.Tensor(
[[0 1]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))

6. `Ragged Tensors`: Ragged tensors are used to represent tensors with varying lengths along one or more dimensions. They are useful for sequences or nested data structures.

In [15]:
# Creating a ragged tensor
values = tf.ragged.constant([[1, 2], [3, 4, 5], [6]])

In [16]:
values

<tf.RaggedTensor [[1, 2], [3, 4, 5], [6]]>

7. `TensorArray`: TensorArray is a dynamic data structure that allows you to store tensors of different shapes and sizes. It's often used in dynamic loop constructs.

In [17]:
# Creating a TensorArray
ta = tf.TensorArray(dtype=tf.float32, size=0, dynamic_size=True)

In [18]:
ta

## Q2. How does TensorFlow constant differ from TensorFlow Variable? Explain with example
---

### Both TensorFlow constants and variables are fundamental data structures, but they have different purposes and behaviors within a TensorFlow computation graph.

## TensorFlow Constants:
- Constants are tensors with fixed values that remain unchanged throughout the computation.
- They are typically used to provide inputs or fixed values to the computation graph.
- Constants cannot be modified or updated after they are created.

## TensorFlow Variables:
- Variables are tensors that hold mutable state, often used for model parameters that need to be learned during training.
- They are initialized with initial values and can be updated through operations like assignments.
- Variables can be used to store and update values as the model iteratively adjusts its parameters during training.

Let's illustrate the difference with examples:

**Example of TensorFlow Constant:**

In [19]:
import tensorflow as tf

# Creating a constant
a = tf.constant(4)

# Attempting to assign a new value to a constant will result in an error
try:
    a.assign(8)  # This will raise an error
except Exception as e:
    print("Error:", e)

Error: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'


**Example of TensorFlow Variable:**

In [20]:
import tensorflow as tf

# Creating a variable with an initial value
initial_value = tf.random.normal(shape=(3, 3))
b = tf.Variable(initial_value)

print("Initial 'b':",b)

# Assigning a new value to the variable using the assign() operation
new_value = tf.random.normal(shape=(3, 3))
b.assign(new_value)

# Now 'b' holds the new value assigned to it
print("\nUpdated 'b':", b)

Initial 'b': <tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[ 1.0866971 ,  1.0040342 , -0.99309117],
       [-0.1838116 , -1.8002889 , -0.48294345],
       [-1.1167066 ,  0.85398287,  1.1814251 ]], dtype=float32)>

Updated 'b': <tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[ 1.5529047 , -1.5110285 , -1.7178645 ],
       [ 0.96474385,  0.2063866 , -1.0428071 ],
       [ 0.17149894,  0.28885084, -0.8135703 ]], dtype=float32)>


### In the second example, you can see that a TensorFlow variable b is created with an initial value. Unlike constants, variables can be assigned new values using the assign() operation. This capability is crucial during the training process, where model parameters (weights and biases) are updated iteratively to minimize the loss function.

### In summary, constants are used to provide fixed inputs or values, while variables are used to hold and update mutable state, often representing model parameters.

---
---

## Q3. Describe the process of matrix addition, multiplication and element wise operations in Tensorflow.
---

### 1.Matrix Addition:

Matrix addition is a basic arithmetic operation where corresponding elements of two matrices are added together to create a new matrix of the same dimensions. In TensorFlow, you can perform matrix addition using the tf.add() function or by using the + operator.

In [21]:
import tensorflow as tf

# Define two matrices
matrix_a = tf.constant([[1, 2], [3, 4]])
matrix_b = tf.constant([[5, 6], [7, 8]])

# Perform matrix addition
result = tf.add(matrix_a, matrix_b)

# Alternatively, you can use the + operator
result_alternative = matrix_a + matrix_b

print("Matrix Addition Result:")
print(result.numpy())
print(result_alternative.numpy())

Matrix Addition Result:
[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


### 2. Matrix Multiplication:

Matrix multiplication is a more complex operation where the dot product of rows and columns of two matrices results in a new matrix. TensorFlow provides the tf.matmul() function to perform matrix multiplication.

In [22]:
import tensorflow as tf

# Define two matrices
matrix_a = tf.constant([[1, 2], [3, 4]])
matrix_b = tf.constant([[5, 6], [7, 8]])

# Perform matrix multiplication
result = tf.matmul(matrix_a, matrix_b)

print("Matrix Multiplication Result:")
print(result.numpy())

Matrix Multiplication Result:
[[19 22]
 [43 50]]


### 3. Element-wise Operations:
Element-wise operations involve applying an operation to each corresponding element of two matrices (or a matrix and a scalar). TensorFlow allows you to perform a variety of element-wise operations, such as addition, subtraction, multiplication, division, and more.

In [23]:
import tensorflow as tf

# Define a matrix and a scalar
matrix = tf.constant([[1, 2], [3, 4]])
scalar = 2

# Perform element-wise addition
result_add = matrix + scalar

# Perform element-wise multiplication
result_multiply = matrix * scalar

print("Element-wise Addition Result:")
print(result_add.numpy())

print("Element-wise Multiplication Result:")
print(result_multiply.numpy())

Element-wise Addition Result:
[[3 4]
 [5 6]]
Element-wise Multiplication Result:
[[2 4]
 [6 8]]


### In TensorFlow, these operations are efficiently handled using optimized numerical libraries, such as Intel MKL and NVIDIA cuBLAS, for CPU and GPU computation, respectively. These libraries allow TensorFlow to take advantage of hardware acceleration for faster computation.

### Remember that proper matrix dimensions and compatibility are crucial for matrix multiplication. The number of columns in the first matrix must match the number of rows in the second matrix for successful matrix multiplication. Element-wise operations require matrices or tensors to have the same shape or be broadcastable.

---
---

**Part 2: Practical Implementation**

# Task 1 : Creating and Manipulating matrices
---

## Q1. Create a normal matrix A with dimensions 3x3, using Tensorflows random normal function. Display the value of matrix A.
---

In [24]:
import tensorflow as tf

# Create a 3x3 matrix with random values from a normal distribution
A = tf.random.normal(shape=(3, 3))

# Display the value of matrix A
print("Matrix A:")
print(A)

Matrix A:
tf.Tensor(
[[ 0.7514016  -0.01408595 -0.63111496]
 [ 0.31570026 -1.2345266  -1.6878096 ]
 [-0.27566957 -1.2404485   1.8445723 ]], shape=(3, 3), dtype=float32)


## Q2. Create a Gaussian Matrix B with dimension 4X4, using truncated_normal function. Display the values of Matrix B
---

In [25]:
import tensorflow as tf

# Define the dimensions of the matrix
matrix_shape = (4, 4)

# Generate a Gaussian matrix using truncated normal distribution
mean = 0
stddev = 1
B = tf.random.truncated_normal(shape=matrix_shape, mean=mean, stddev=stddev)

# Display the generated matrix
print("Matrix B:")
print(B.numpy())

Matrix B:
[[-0.7251475  -0.8183251   1.3367926  -0.62212795]
 [ 0.55693215 -0.3758494  -1.2475643   0.46360412]
 [-1.5733156   0.15936531  0.4544715  -1.8297238 ]
 [-0.09446213  0.5764355  -1.1420331   0.88677186]]


## Q3. Create a Gaussian Matrix C with dimension 2X2, where values are drawn from normal distribution with a mean of 3 and a standard deviation of 0.5, using Tensorflow's random.normal function Display values of matrix C.
---

In [26]:
import tensorflow as tf

# Define the dimensions of the matrix
matrix_shape = (2, 2)

# Generate a Gaussian matrix using normal distribution
mean = 3.0
stddev = 0.5
C = tf.random.normal(shape=matrix_shape, mean=mean, stddev=stddev)

# Display the generated matrix
print("Matrix C:")
print(C.numpy())

Matrix C:
[[3.5583296 3.162041 ]
 [2.8106625 2.7886827]]


## Q4. Perform matrix addition between matrix A and matrix B and store the results in matrix D
---

### Matrix A has shape (3,3) while matrix B has shape(4,4) it is not possible to add these matrices as shapes are different
Below is alternate example to show matrix addition

In [27]:
matrix1 = tf.random.normal(shape=(2,2))
matrix2 = tf.random.normal(shape=(2,2))
D = tf.add(matrix1, matrix2)
print(f'Matrix 1 :\n {matrix1.numpy()}')
print(f'\nMatrix 2 :\n {matrix2.numpy()}')
print(f'\nMatrix D :\n {D.numpy()}')

Matrix 1 :
 [[ 0.00797569 -0.9015963 ]
 [ 0.7706862  -0.59166795]]

Matrix 2 :
 [[-0.77476656 -0.3084806 ]
 [ 1.7242459   1.1012186 ]]

Matrix D :
 [[-0.76679087 -1.2100769 ]
 [ 2.4949322   0.50955063]]


## Q5. Perform matrix multiplication between  matrix C and matrix D and store result in matrix E
---

In [28]:
E = tf.matmul(C,D)

print(f'Matrix C :\n{C.numpy()}')
print(f'\nMatrix D :\n{D.numpy()}')
print(f'\nMatrix E = CxD:\n{E.numpy()}')

Matrix C :
[[3.5583296 3.162041 ]
 [2.8106625 2.7886827]]

Matrix D :
[[-0.76679087 -1.2100769 ]
 [ 2.4949322   0.50955063]]

Matrix E = CxD:
[[ 5.160583  -2.6946325]
 [ 4.8023844 -1.9801428]]


---
---

# Task 2: Performing additional matrix operations
---

## Q1. Create a matrix F with dimensions 3x3, initialized random values using Tensorflows random_uniform function.
---

In [29]:
# Create a matrix F
F = tf.random.uniform(shape=(3,3))
print(f'Matrix F :\n{F.numpy()}')

Matrix F :
[[0.90427613 0.6640326  0.54985905]
 [0.9693881  0.28900433 0.22192848]
 [0.8901019  0.6965618  0.42168522]]


## Q2. Calculate Transpose of Matrix F and store in Matrix G
---

In [30]:
# Transpose the F matrix
G = tf.transpose(F)

# Print the matrix
print(f'Matrix G :\n{G.numpy()}')

Matrix G :
[[0.90427613 0.9693881  0.8901019 ]
 [0.6640326  0.28900433 0.6965618 ]
 [0.54985905 0.22192848 0.42168522]]


## Q3. Calculate element wise exponential of Matrix F and store the result in matrix H
---

In [31]:
# Element wise exponent
H = tf.math.exp(F)

# Print matrix H
print(f'Matrix H :\n{H.numpy()}')

Matrix H :
[[2.4701433 1.9426103 1.7330087]
 [2.6363308 1.3350976 1.2484821]
 [2.4353778 2.006841  1.5245285]]


## Q4. Create a matrix I by concatenating Matrix F and matrix G horizontally
---

In [32]:
# Concatenate matrices F and G horizontally to create matrix I
I = tf.concat([F, G], axis=1)

# Display the original matrices and the concatenated matrix
print("Matrix F:")
print(F.numpy())

print("\nMatrix G:")
print(G.numpy())

print("\nMatrix I (Concatenated Horizontally):")
print(I.numpy())

Matrix F:
[[0.90427613 0.6640326  0.54985905]
 [0.9693881  0.28900433 0.22192848]
 [0.8901019  0.6965618  0.42168522]]

Matrix G:
[[0.90427613 0.9693881  0.8901019 ]
 [0.6640326  0.28900433 0.6965618 ]
 [0.54985905 0.22192848 0.42168522]]

Matrix I (Concatenated Horizontally):
[[0.90427613 0.6640326  0.54985905 0.90427613 0.9693881  0.8901019 ]
 [0.9693881  0.28900433 0.22192848 0.6640326  0.28900433 0.6965618 ]
 [0.8901019  0.6965618  0.42168522 0.54985905 0.22192848 0.42168522]]


## Q5. Create a matrix J by concatenating matrix F and matrix H vertically
---

In [33]:
# Concatenate matrices F and H vertically to create matrix J
J = tf.concat([F, H], axis=0)

# Display the original matrices and the concatenated matrix
print("Matrix F:")
print(F.numpy())

print("\nMatrix H:")
print(H.numpy())

print("\nMatrix J (Concatenated Vertically):")
print(J.numpy())

Matrix F:
[[0.90427613 0.6640326  0.54985905]
 [0.9693881  0.28900433 0.22192848]
 [0.8901019  0.6965618  0.42168522]]

Matrix H:
[[2.4701433 1.9426103 1.7330087]
 [2.6363308 1.3350976 1.2484821]
 [2.4353778 2.006841  1.5245285]]

Matrix J (Concatenated Vertically):
[[0.90427613 0.6640326  0.54985905]
 [0.9693881  0.28900433 0.22192848]
 [0.8901019  0.6965618  0.42168522]
 [2.4701433  1.9426103  1.7330087 ]
 [2.6363308  1.3350976  1.2484821 ]
 [2.4353778  2.006841   1.5245285 ]]
